### ISSUE TITLE
vs hyper-h2

### ISSUE THREAD

**Issue by merrellb** [njsmith/h11#44]
I notice that hyper-h2 was an inspiration for h11 but it isn't clear to me how they differ.  My quick read of the hyper-h2 documentation seems to suggest that it also supports HTTP 1.1 and takes a similar implementation neutral approach.   What factors would lead one to use h11 vs hyper-h2?

**Comment by Lukasa** [comment]
Hey there!

So, hyper-h2 does not support HTTP/1.1: if it gave that impression I need to clear it up. HTTP/2 is sufficiently different that there would be very little common code between the protocol stacks, which means there is relatively little advantage in unifying them (though at some point I might write a wrapper that handles upgrade and stuff cleanly).

As to some differences:

- hyper-h2 eagerly parses data when `receive_data` is called, while h11 delays parsing until calling `next_event`. In general I think h11's strategy is better here, but it came later and could learn from my mistakes. 😉
- hyper-h2 has vastly more code. HTTP/2 is a vastly more complex protocol than HTTP/1.1 in terms of state management. 
- h11 uses events as inputs as well as outputs, while hyper-h2 has the user call a bunch of differently named functions instead of "sending" events.

**Comment by merrellb** [comment]
Hey Lukasa,

Thanks for the quick reply and good points of comparison!  Regarding HTTP/1.1, I think my confusion came from the 3.0.0 release note:

```This release was motivated primarily by discovering that applications that attempted to use both HTTP/1.1 and HTTP/2 using hyper-h2 would encounter problems with cookies, because hyper-h2 did not join together cookie headers as required by RFC 7540.```

**Comment by Lukasa** [comment]
Ah yeah, that's not super clear. "Using hyper-h2" was supposed to be a qualifier to "HTTP/2", but I can see the confusion there. 😟

**Comment by njsmith** [comment]
Sounds like you two worked this out. (Thanks!)
