### ISSUE TITLE
Not sure how else to get in touch :-)

### ISSUE THREAD

**Issue by njsmith** [njsmith/h11#53]
@nikratio Did you figure out your issue with AWS request signing?

**Comment by Nikratio** [comment]
You can email me at Nikolaus@rath.org :-).

Not fully. I believe it was connected to the client sending `Connection: keep-alive` for HTTP 1.1 connections so I got rid of that (assuming that maybe h11 stripping that out because it's implicit). That fixed the problem, but I also did a bunch of other changes at the same time, so I never confirmed the root cause. That's why I deleted the comment again.

**Comment by njsmith** [comment]
`Connection: keep-alive` is a non-standard and obsolete feature, and I've never found decent docs on how programs expect it to work in practice. Plus it has weird failure modes. So currently h11 doesn't support it.

I believe that h11 allows you to specify `Connection: keep-alive` in a client request if you really want to, but it doesn't do anything: if the server turns out to speak HTTP/1.1 then it's redundant (equivalent to not sending the header at all), and if it turns out to speak HTTP/1.0 then h11 disables keepalive anyway.

In a server response, h11 doesn't allow you to send `connection: keep-alive`. But you were talking about making requests to AWS, and I assume you aren't implementing AWS, so probably the client part is what matters.

Anyway, file a bug if you have any more trouble...
